package com.locker.tictactoe.presentation.theme

const val SCREEN_CHANGE_ANIM_DURATION = 500
const val PALETTE_SLIDE_ANIM_DURATION = 1000
const val COLOR_PICKED_ANIM_DURATION = 500
const val THEME_COLORS_CHANGE_ANIM_DURATION = 1000

const val VERY_LOW_STIFFNESS = 20f

const val FADE_WIN_BLOCK_TIME = 3000

const val NEXT_GAME_SCREEN_CHANGE_ANIM_DURATION = FADE_WIN_BLOCK_TIME
const val NEXT_GAME_SCREEN_CHANGE_DELAY_DURATION = 1000

const val SUB_FIELD_LINE_LENGTH_PERCENT = 0.8f

const val LOW_ALPHA = 0.2f
const val HALF_ALPHA = 0.5f

const val MENU_BUTTON_PERCENT = 0.8f

const val MIN_INNER_COLOR_PERCENT = 0.6f
const val MAX_INNER_COLOR_PERCENT = 0.8f
